version: "3.9"

services:
  db:
    image: postgres:15
    container_name: urlshortener_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d  
    networks:
      - appnet

  app:
    build: .
    container_name: urlshortener_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/urlshortener?sslmode=disable
      - PORT=8080
      - BASE_URL=http://localhost:8080
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
